[package]
name = "rec"
version = "0.1.0"
authors = ["bonal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
plotters = "0.3.1"
fltk = { version = "^1.2", features = ["fltk-bundled"] }
